version: '3.9'

services:
  database:
    container_name: walmart-api-db
    image: mysql:8
    ports:
      - "3307:3306"
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE: walmart-db
      MYSQL_ROOT_PASSWORD: walmapi
      MYSQL_USER: walmapi
      MYSQL_PASSWORD: walmapi
    volumes:
      - walmart-api-volume:/var/lib/mysql
    restart: always

volumes:
  walmart-api-volume: